apiVersion: v1
kind: PersistentVolume
metadata:
  name: weather-postgres-pv
spec:
  capacity:
    storage: 5Gi

  accessModes:
    - ReadWriteOnce

  persistentVolumeReclaimPolicy: Retain

  storageClassName: ""

  hostPath:
    path: /var/lib/weather-postgres-data
    type: DirectoryOrCreate

---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: weather-postgres-pvc
  namespace: weather
spec:
  accessModes:
    - ReadWriteOnce

  resources:
    requests:
      storage: 5Gi

  storageClassName: ""

  volumeName: weather-postgres-pv
